- src/infiniteGrid.js
- test/js/infiniteGrid.test.js
When using setStatus getGroupKeys method always returns []
because setStatus method didn't manage `_isLayoutInited` property.
#11
@taihoon-kim  @happyhj
> fix(infiniteGrid): fix restore/store bug

- Gruntfile.js
- config/clean.js
- package.json
- remove clean task
- adjust grunt-contrib-clean
#3 
@happyhj  @happyhj
> Cleantask#3

- src/infiniteGrid.js
- test/js/infiniteGrid.test.js
- fix bug about issue
- rearrange testcase
#45
@jongmoon  @taihoon-kim
> When DOM prepend more than option

- src/flicking.js
- src/hook/animate.js
#52
Support Korean
@sculove  @jongmoon
> doc(flicking, animate) : Support Korean

- src/infiniteGrid.js
- test/js/infiniteGrid.test.js
- expand methods like appand, prepend.
- append and prepend method support `concated string`, `HTMLElement array`, `jQuery` type.
#1 
@mixed  @netil
> Expand methods like append, prepend

- src/class.js
- src/component.js
- test/js/class.test.js
- test/js/component.test.js
#59 
Move instance method to eg.class from eg.component 
Update test
@sculove @mixed
> Instance#59 : move 'instance' method to 'class' 

- src/customEvent/rotate.js
- test/js/rotate.test.js
- eg.isPortrait returns 'null' first time
- correct test comment
#107
@happyhj @mixed
> fix(rotate): fix isPortrait value

- bower.json
- change outlayer version in bower.json
#87
> chore(bower): change outlayer version

- .github/PULL_REQUEST_TEMPLATE.md
#136
Changed group id @egjs-dev ==> @naver/egjs-dev
> style(template): Correction on egjs group id

- src/infiniteGrid.js
- test/unit/infiniteGrid.test.html
- test/unit/js/infiniteGrid.test.js
ref #121
fix testcases bug for IE8
@happyhj
> fix(infiniteGrid): fix testcase infiniteGrid for IE8

- config/concat.js
- config/dependency.js
- src/hook/cssPrefix.js
- src/hook/transform.js
- test/manual/cssPrefix.html
- test/manual/flicking.html
- test/manual/infiniteGird_demo.html
- test/manual/infiniteGrid.html
- test/manual/movableCoord.html
- test/manual/movableCoord_basic.html
- test/manual/persist.html
- test/manual/transform.html
- test/manual/visible.html
- test/unit/cssPrefix.test.html
- test/unit/js/cssPrefix.test.js
- test/unit/js/transform.test.js
- test/unit/transform.test.html
#183 
Change hook names.
css --> cssPrefix
animate --> transform
> chore(css): Change file names of hook

- demo/flicking.html
#181 
Supplement flicking documentation.
Add some explanations related with CSS height property.
@netil @sculove
> chore(Flicking): supplement documentation.

- src/infiniteGrid.js
- test/unit/js/infiniteGrid.test.js
#211 
infiniteGrid can't restore properties of 'null' value
somebody
> fix(infiniteGrid): check 'null' value in setStatus

- src/class.js
- src/component.js
- src/customEvent/scrollEnd.js
- src/flicking.js
- src/hook/cssPrefix.js
- src/hook/pauseResume.js
- src/hook/transform.js
- src/infiniteGrid.js
- src/movableCoord.js
- src/plugin/persist.js
- src/visible.js
#4 
Add edge field on `@support` tag in jsdoc Documentation.
like below
```js
@support {/*...*/, "edge" : "latest"}
```
> chore(all): Add EDGE support to jsdoc "support" tag

- README-ko.md
- README.md
> docs(README): update cdnjs url

- test/manual/pauseResume.html
#209
Modify pauseResume manaul test cases.
**Add a button which controls pause/resume like below.**
This makes pauseResume testable on mobile browser.
> test(pauseResume): Make pauseResume testable on mobile browser

- src/customEvent/rotate.js
- src/customEvent/scrollEnd.js
Missing @param.
@sculove @jongmoon 
Ref #207
> doc(scrollend, rotate): Missing @param

- assets/css/item.css
- src/infiniteGrid.js
- test/manual/infiniteGird_demo.html
#149 
infiniteGrid couldn't use -webkit-line-clamp property.
@somebody
> fix(infiniteGrid): deal with -webkit-line-clamp

- src/infiniteGrid.js
- test/manual/infiniteGird_demo.html
- test/unit/js/infiniteGrid.test.js
#249
To restore status, I fix some code at onScroll handler
somebody
@happyhj @kishu
> fix(infiniteGrid): deal with defence code

- config/commit.template
- config/validate-commit-msg.js
#254 
fix guidline link.
@mixed @kishu
> chore(commit.template): fix commit log guidlines link

- config/commit.template
> chore(commit): add types description

- src/infiniteGrid.js
#247 
- add detail comments.
- plz, check korea comments 
> docs(InfiniteGrid): reinforce a description about eg.InfiniteGrid

- src/infiniteGrid.js
- test/unit/js/infiniteGrid.test.js
#273
prevent for "Converting circular stucture to JSON" issue.
samsung browers(4.4.2/4.3) have only bugs.
@happyhj @kishu
> fix(infiniteGrid): add defence code for cross-browser

- config/validate-commit-msg.js
#261
- Add ignore case option
- Fixed folder path
If you do not work hook. [check it](https://github.com/naver/egjs/issues/261#issuecomment-230486565)
@happyhj @sculove @netil
> Fixed commit validate

- src/movableCoord.js
#247 
- reinforce document about movableCoord
> docs(MovableCoord): reinforce document

- src/component.js
- src/customEvent/rotate.js
- src/hook/cssPrefix.js
#277
enhance documation
@naver/egjs-committers
> doc(component, rotate, cssPrefix): enhance document

- src/class.js
#294
enhance document for eg.Class
> docs(class): enhance document for eg.Class

- test/manual/persist.html
#250
* Change Korean to English in demo.
* Remove deprecated api in demo code.
@jongmoon, @netil
> test(persist): wipe use of deprecated api from demo

- src/eg.js
> docs(eg): Reinforcement document

- src/customEvent/scrollEnd.js
> docs(scrollEnd): Reinforcement document

- src/hook/pauseResume.js
- src/hook/transform.js
#299 
enhance the transform/pauseResume documents.
> docs(transform): enhance the transform/pauseResume documents.

- src/plugin/persist.js
> docs(persist): Reinforce document

- src/visible.js
#296 
Improve descriptions on jsdoc
> docs(visible): Reinforce document

- README-ko.md
- README.md
#308 
- remove outlayer.
- synchronize documents.
plz, check [this document](https://github.com/naver/egjs/wiki/Download-and-Using-egjs). 
> docs(README): update README

- src/module.js
- test/unit/buildMerge.min.test.html
- test/unit/buildMerge.test.html
#282 
- remove outlayer dependency at module.js
@mixed
> chore(module): remove outlayer

- test/manual/flicking.html
- test/manual/movableCoord.html
- test/manual/movableCoord_basic.html
- test/manual/persist.html
- test/manual/rotate.html
- test/manual/scrollEnd.html
- test/manual/visible.html
#323 
- add dependency in manual test files.
@netil
> chore(all): add agent dependency

- src/plugin/persist.js
- test/unit/js/persist.test.js
- test/unit/persist.test.html
#352, #324 
- remove eg dependency
- change from 'jQuery' to '$'
@happyhj
> Remove eg dependency#352

- config/exec.js
#354
Treat 'refactor' prefixed item.
Surpass if no items found.
> chore(changelog): refactor item commit inclusion

- .editorconfig
#256
We have to same editor config for unnecessary change code. This config have applid currently all files.
@naver/egjs-committers
> chore(all): Add .editorconfig

- config/exec.js
#368
Added to handle `docs, style and chore` tags.
Changed boundary regex patterns.
```bash
$ grunt changelog:2016-06-09
```
- **Flicking**
- Handle when container element is given ([#216](https://github.com/naver/egjs/issues/216))
- Deprecate .getTotalCount() and index prop event ([#229](https://github.com/naver/egjs/issues/229))
- Implement distance prop on flick event ([#218](https://github.com/naver/egjs/issues/218))
- Remove .getTotalCount() and index prop event ([#229](https://github.com/naver/egjs/issues/229))
- **InfiniteGrid**
- Remove outlayer dependency ([#282](https://github.com/naver/egjs/issues/282))
- **Flicking**
- Prevent API move call during touch hold ([#268](https://github.com/naver/egjs/issues/268))
- Correct panel sizing on padding …
> chore(changelog): Handle all commit tags

- test/unit/js/flicking.test.js
#362
Update to not be erroneous on jQuery 3.
@jongmoon
> test(flicking): Assertion condition update

- config/banner.js
#379
Removed `egjs-cli` from comment banner
@happyhj
> chore(banner): Remove outdated info

- config/concat.js
- src/eg.js
- src/raf.js
- test/unit/flicking.test.html
- test/unit/js/raf.test.js
- test/unit/movableCoord.test.html
- test/unit/raf.test.html
#364
- add timestamp parameter
- raf separate from egCore
@netil @sculove
> fix(eg): Missing timestamp

- src/movableCoord.js
- test/manual/flicking.html
- test/manual/movableCoord.html
- test/manual/movableCoord_basic.html
- test/unit/js/movableCoord.test.js
#389 
- add `getHammer` method.
- refactoring duplicated code `_getEl`
- add raf.js in demos
- correct descriptions
@happyhj
> feat(MovableCoord): add getHammer method

- src/plugin/persist.js
- test/unit/js/persist.test.js
- test/unit/persist.test.html
#373 
Now can set values like null, undefined, '' with setter API
> feat(persist): can remove value with setting empty values

- README.md
- src/hook/cssPrefix.js
> update cssPrefix docs.

- src/visible.js
- test/unit/js/visible.test.js
#365 
Add the branch code of condition 'containment'.
Add Test codes.
Improve docs.
@sculove
> feat(visible): check 'containment' elements

- src/customEvent/scrollEnd.js
- test/unit/js/scrollEnd.test.js
> refactor(scrollEnd): remove dependency agent

- README-ko.md
- README.md
> chore(dev-env): Fixed format

- src/component.js
> chore(component): Fixed documention.

- src/infiniteGrid.js
- test/unit/js/infiniteGrid.test.js
#462, #466 
- support multi direction.
- infiniteGrid can use prepend items at the first time.
- correct croppedCount in layoutComplete event.
@netil
> feat(infiniteGrid): support multi direction.

- src/movableCoord.js
- test/unit/js/movableCoord.test.js
#459 
- supports disable/enable input
@netil
> feat(movableCoord): add disable/enableInput

- src/infiniteGrid.js
- test/unit/js/infiniteGrid.test.js
#447
- add workaround for IE
@netil
> fix(infiniteGrid): workaround for IE

- src/infiniteGrid.js
- test/unit/js/infiniteGrid.test.js
#477
- fix side-effect about refactoring
- fix getBottomElement method bug
- add testcase
@netil
> fix(infiniteGrid): fix side-effect bug

- src/agent.js
- test/unit/js/agent_info.js
#451 
Support Opera Browser
approve PR (#451) and fix the version rule and coding convention.
@happyhj @sculove
> Support Opera Browser

- src/flicking.js
- test/unit/js/flicking.test.js
#492 
Set condition check on resize
> fix(flicking): Prevent resize during panel animation

- README.md
- package-lock.json
- package.json
> chore(egjs): Change to latest version in package.json
