test/js/eg.test.js
Change Array.prototype.forEach, Array.prototype.map method to jQuery.forEach and jQuery.map
for old IE support
#28 
@taihoon-kim  @sculove
=> test(animate): Make unit tests support old IE

test/js/animate.test.js
Set QUnit reorder option false.
Adjust value. because only IE makes negative zero string. This makes test failure on IE.
#31 
@netil  @jongmoon
=> test(animate): Set QUnit reorder option false

src/component.js, test/js/component.test.js
#51 
The required initiallization of options property was missing.
So I put the initialization code.
Pull my code or write example to the api doc.(See the code below)
```javascript
var MyComponent = eg.Class.extend(eg.Component,{
"construct" : function(option){
// initialize options property here
this.options = option;
}
});
```
@sculove @taihoon-kim
=> fix(component): initialize options property

test/js/movableCoord.test.js, test/js/visible.test.js
- Target testcases like visible, movableCoord are changed from asyncTest to test because asyncTest will be deprecated in Qunit 3.0
#48 
@happyhj  @jongmoon
=> Change async test#48

README.md
egjs/egjs.github.io/issues/2
Although It has README-ko.md It have broken korean link in API document.
So I changed korean document link path.
@taihoon-kim @sculove
=> docs(index): change korean doc link path

src/movableCoord.js, test/js/movableCoord.test.js
#42 
Make _convertInputType method stateless and Update tests
@sculove @kishu
=> refactor(movableCoord): Make _convertInputType stateless

src/hook/animate.js, test/manual/animate.html, test/unit/js/animate.test.js
#166 
Support rotate3d and fix interpolation bug on rotation.
=> Support rotate3d and fix interpolation bug on rotation.

src/hook/pauseResume.js, test/manual/pauseResume.html, test/unit/js/pauseResume.test.js
#167 
Support pause/resume on $.fn.delay
@happyhj, @naver/egjs-dev
=> eg.pauseResume - support pause/resume on $.fn.delay

src/customEvent/rotate.js, test/manual/rotate.html, test/unit/js/rotate.test.js
#182 
```js
$(window).on("resize", function() { 
if (eg.isPortrait()) { 
//do something...
}
}); 
$(window).on("rotate",function(e){
// Not Fired		
});
```
isPortrait( ) affects the 'rotate' event firing. because When it is called, it changes the status value(`beforeScreenWidth`)   which is referenced by isVertical() (in next step) to decide if it is needed firing a "rotate" custom event.
@mixed , @sculove, @happyhj 
@mixed I tried to move `beforeScreenWidth` to the `handle( )` function as you told me. But I think `triggerRotate( )` is more proper because `beforeScreenWidth` must be changed after `isVertical` (by triggerRotate) is called.
=> fix(rotate): Rotate event is not fired In certain cases

src/infiniteGrid.js, test/unit/js/infiniteGrid.test.js
#161 
- When the parameter  is not appropriate for setStatus method, a script error is fired.
@jongmoon @happyhj
=> fix(infiniteGrid): add defense code in setStatus method

src/movableCoord.js, test/unit/js/movableCoord.test.js
#195 
Fix the bug which prevent user interaction after no change move.
When user try to move position but If no changes occurs _(caused by MC.DIRECTION_XXX FLAG or insufficient user movement for moving position)_, then **there's no chance to set interrupt flag to false**. It makes user interaction unavailable.
@sculove @happyhj
=> fix(MovableCoord): Unlock interrupt flag after no move.

Gruntfile.js, package.json
#197
chore(all): Remove unit testing task from prepush hook
* add listing grunt task "grunt lint"
* modify prepush hook to use "grunt lint" command 
@naver/egjs-committers  @sculove   @jongmoon
=> chore(all): Remove unit testing task from prepush hook

src/plugin/persist.js, test/unit/js/persist.test.js
#199
fix(persist): don't show warning message on clean storage
* Make persist don't show warning message when storage is clean.
@naver/egjs-committers  @mixed @jongmoon
=> fix(persist): don't show warning message on clean storage

config/validate-commit-msg.js
Keyword skip commit log validation that have changed `WIP` to `skip`.
=> chore(commit): Bypass keyword change WIP to skip

src/infiniteGrid.js, test/manual/infiniteGird_demo.html, test/unit/js/infiniteGrid.test.js
#178
- add _waitResource method
- add defence code at event handlers
- change _waitImageLoaded interface.
- some code refactoring
=> fix(infiniteGrid): check image size when initializing

src/customEvent/rotate.js, src/customEvent/scrollEnd.js, test/manual/rotate.html, test/unit/js/rotate.test.js, test/unit/js/scrollEnd.test.js
#174
- Add jQuery style
- Fixed documention
- Add testcase
- Fixed documention
- Add testcase
@jongmoon @happyhj
=> fix(srollend,rotate) : Event style have changed jindo to jquery.

src/plugin/persist.js
#233 
#234 
* Replace cached location with global.location
* Add try catch block on storage.getItem() in **isStorageAvailable** method
@sculove, @jongmoon
=> fix(persist): add IE8 exception handling

jsdoc.json
#271
Support markdown on @ko Tag in jsdoc documentation
like below,
```html
/**
* @ko 안녕하세요! **굵은글씨**도 가능하고 이미지도 연결 할 수 있어요 ![YourImage](http://....)
*/
```
@sculove @naver/egjs-dev
=> chore(all): support jsdoc setting to support ko tag

src/hook/pauseResume.js, test/unit/js/pauseResume.test.js
#274
When you call stop() on elements which is not animated,
script error occurs because __aniProp is not exist.
=> fix(pauseResume): Fix a script error on stop()

src/infiniteGrid.js, test/unit/js/infiniteGrid.test.js
#263 
If the infiniteGrid haven't element and 'scroll' event is fired, we face a problem.
@kishu @netil
=> fix(InfiniteGrid): add defense code on scroll

src/infiniteGrid.js
#309 
IE9 couldn't unaware `load` event of images 
@kishu
=> fix(infiniteGrid): fix image check module in IE9

src/movableCoord.js, test/unit/js/movableCoord.test.js
#288 
Although direction of movement is different from options.direction, MC should fire 'release' event.
@sculove, @netil, @mixed 
@netil it's related with `eg.flicking`
=> fix(MovableCoord): fire release event

src/movableCoord.js, test/unit/js/movableCoord.test.js
#189 
- fix bug when options is null
- change qunt2.x style
@jongmoon
=> fix(movableCoord): fix options bug

src/infiniteGrid.js, test/manual/infiniteGird_demo.html
#325 
- improve image check logic
- [improve LayoutItem function](https://github.com/naver/egjs/issues/325#issuecomment-236477345)
- [improve CheckImageLoaded function](https://github.com/naver/egjs/issues/325#issuecomment-236478639)
- [improve waitImageLoaded function](https://github.com/naver/egjs/issues/325#issuecomment-236493584)
@mixed @netil
=> refactor(infiniteGrid): enhance performance about initialization

src/hook/cssPrefix.js, test/unit/js/cssPrefix.test.js
#196 
- fix logic that checks jQuery version.
- change Qunit 2.x style
@kishu
=> fix(cssPrefix): fix logic that checks jQuery version

src/hook/pauseResume.js
#340 
Do not convert transform's relative values to absolute values. Because pauseResume does not support "transform" property yet.
We will going to enhance this issue on #242 . Before this, we need temporary measure.
=> fix(pauseResume): Don't convert relative values of transform string.

src/infiniteGrid.js
#269 
- deprecated `fit` method
- remove itemSelector options
@kishu
=> docs(infiniteGrid): remove fit method and itemSeletor options

.travis.yml
#363
0.10.40 to 4 (latest 4.x release)
Agreed to upgrade to 4.5, but Travis doesn't have that version.
- https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Available-Versions
Just declaring major version "4" will run `4 latest 4.x release`.
=> chore(dev-env): Upgrade nodejs version on Travis

src/movableCoord.js, test/unit/js/movableCoord.test.js
#378 
- clean resource after destruction
- remove element attribute in destroy
@happyhj
=> fix(MovableCoord): clean resource after destruction

src/movableCoord.js, test/unit/js/movableCoord.test.js
#431 
support Hammer 2.0.4/2.0.5
@netil
=> fix(MovableCoord): add support Hammer 2.0.4, 2.0.5

src/component.js, test/unit/js/component.test.js
Ref #412
once is executed event just one time.
@happyhj @jongmoon
=> feat(component): add once method

src/flicking.js, test/unit/js/flicking.test.js
#436
Fixed param value on evaluating direction.
(#436 issue happens because of wrong direction value on calling `.moveTo()`)
@sculove
=> fix(flicking): Corrected direction param on .moveTo()

src/agent.js, test/unit/js/agent_info.js
Makes iOS WebView returns `-1` as a browser version. Because iOS WebView version's consistency
#440 
eg.agent returns invalid borwser version from webview on iPad (iOS 10.0.2)
@happyhj @sculove
=> fix(agent): invalid browser version of iOS WebView

src/flicking.js, test/unit/js/flicking.test.js
#445 
When adpativeHeight option is set and moved by .moveTo(),
correct getting target panel element
@sculove
=> fix(flicking): Fix getting target panel for adaptiveHeight

src/flicking.js, test/unit/flicking.test.html, test/unit/js/flicking.test.js
#438
When container element is given,
corrected referencing panel elements properly.
@sculove
=> fix(flicking): Fix wrong referencing of panel elements

src/infiniteGrid.js, test/manual/infiniteGrid.html, test/unit/infiniteGrid.test.html, test/unit/js/infiniteGrid.test.js
#461, #454 
- supports remove method
- supports layout(isReloyout)
- refactoring layout
- correct getStatus jsdoc (#454)
@netil
=> Remove#461

src/infiniteGrid.js
#461 
- add jsdoc comment
@netil
=> docs(infinitGrid): add jsdoc of remove method.

src/infiniteGrid.js, test/unit/js/infiniteGrid.test.js
#467
- if the position of element is same, getBottomElement returns right element.
- add comment
@netil
=> fix(infiniteGrid): fix return value of getBottomElement

src/infiniteGrid.js, test/unit/js/infiniteGrid.test.js
#450
- add code that reset _prevScrollPos  property after resizing 
@netil
=> fix(infiniteGrid): fire append event after resize

src/infiniteGrid.js, test/unit/js/infiniteGrid.test.js
#455
Call the prepend event three times after the layoutComplete event. 
because user forces the scroll position zero.
@netil
=> fix(infiniteGrid): add defense code when the user forces the scroll

src/flicking.js, test/unit/js/flicking.test.js
#433 
Fixed instead of handling MovableCoord's event binding,
to use MovableCoord's disable/enableInput method.
@sculove
=> fix(flicking): Fix panel position on disableInput mode

src/component.js, src/customEvent/scrollEnd.js, src/hook/pauseResume.js, src/visible.js, test/unit/js/agent.test.js, test/unit/js/class.test.js, test/unit/js/component.test.js, test/unit/js/flicking.test.js, test/unit/js/infiniteGrid.test.js, test/unit/js/persist.test.js, test/unit/js/rotate.test.js, test/unit/js/visible.test.js
* refactor(component): remove unused variable and return value
- Array#splice() changes itself and returns deleted elements. So
assigning return value is not necessary in this case.
* refactor(visible): remove unexecuted codes by above condition
* refactor(scrollEnd): remove unnecessary radix parameter for parseFloat()
- parseFloat() has only one argument unlike parseInt
* refactor(pauseResume): remove unnecessary condition check
- type is set to constant "fx" above
* test(agent): remove uninitialized variable use and fix parseFloat()
* test(class): use previously calculated variable 'nChangedMultiB'
* test(component): remove redundant 'var' because it is function scoped
* test(flicking): move 'var' declaration under its function
* test(infiniteGrid): remove unused variable 'self'
* …
=> refactor: make code clean by removing unused/unnecessary codes

src/flicking.js, test/unit/js/flicking.test.js
#478
In case of rotate(or in case of panel's height changes), need to re-evaluate panel's height value.
This fixes removing 'data-height' attribute and re-evaluate calling ._setAdaptiveHeight().
@sculove
=> fix(flicking): Improve .resize() on adaptiveHeight option

src/flicking.js, test/unit/js/flicking.test.js
#489 
Removed '_checkPadding()'. It doesn't necessarily need to check the difference and applying padding of panels, because call of resize is up to the decision of user.
@sculove
=> fix(flicking): Fix on previewPadding resizing
